# Generated by Django 2.2.6 on 2019-10-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldOne', models.CharField(default='Z', max_length=20)),
                ('fieldTwo', models.IntegerField(default='10')),
                ('color', models.CharField(default='r', max_length=7)),
            ],
        ),
    ]
