# Generated by Django 2.2.6 on 2019-12-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS361WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetime',
            name='instructor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='TA',
        ),
    ]
