# Generated by Django 2.2.6 on 2019-10-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS361WebApp', '0002_auto_20191022_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='myModel',
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CS361WebApp.Account')),
            ],
            bases=('CS361WebApp.account',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CS361WebApp.Account')),
            ],
            bases=('CS361WebApp.account',),
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CS361WebApp.Account')),
            ],
            bases=('CS361WebApp.account',),
        ),
    ]
