# Generated by Django 2.2.6 on 2019-11-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS361WebApp', '0003_auto_20191029_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
            ],
        ),
    ]
