# Generated by Django 2.2.6 on 2019-12-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS361WebApp', '0003_remove_savepriority_mylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepriority',
            name='department',
            field=models.CharField(default='CS', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savepriority',
            name='number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='savepriority',
            name='priority',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='savepriority',
            name='section',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
