# Generated by Django 2.2.6 on 2019-11-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS361WebApp', '0004_coursetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetime',
            name='day',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
