# Generated by Django 2.2.6 on 2019-12-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS361WebApp', '0005_auto_20191205_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepriority',
            name='day',
        ),
        migrations.RemoveField(
            model_name='savepriority',
            name='end',
        ),
        migrations.RemoveField(
            model_name='savepriority',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='savepriority',
            name='start',
        ),
    ]
